config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :wikis
  resources :charges, only: [:new, :create]
  resources :wikis
  resources :collaborators, only: [:new, :create, :destroy]
  get 'charges/downgrade'
  post 'charges/downgrade' 
  get 'charges/validate'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis, through: :collaborators
  has_many :collaborators
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_save { self.email = email.downcase }
  before_save { self.role ||= :standard }
  after_create :send_user_emails


  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  enum role: [:standard, :premium, :admin]


  private

  def send_user_emails
   UserMailer.new_user(self).deliver_now
  end
  
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  #before_validation { self.private = false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
   
   @user = current_user
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 15_00,
     description: "Upgrade to premium membership - #{current_user.email}",
     currency: 'usd'
   )
   current_user.premium!
   flash[:notice] = "Thanks for becoming a premium member #{current_user.email}!"
   redirect_to wikis_path # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end
  
  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Blocipedia membership - #{current_user.email}",
     amount: 15_00
   }
   end
   
  def downgrade
   @user = current_user
   current_user.standard!
   flash[:alert] = "You just downgraded your membership.  SAD!"
   @user.wikis.each do |pub|
   pub.update_attributes(private: false)
  end
   redirect_to root_path
  end
  
  def validate
   render "charges/validate.html.erb"
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
    
  def new
    @coll = Collaborator.new
  end

  def create
 # #9
    @coll = Collaborator.new(wiki_id: params[:wiki_id], user_id: params[:user_id])



 # #10
    if @coll.save
 # #11
       flash[:notice] = "Collaborator was added."
       redirect_to wikis_path
    else
 # #12
       flash.now[:alert] = "There was an error creating the collaborator. Please try again."
       render :new
    end
  end
  
  
  def destroy
      
     @coll = Collaborator.find(params[:id])
 
 # #8
     if @coll.destroy
       flash[:notice] = "\"#{@coll.user_id}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the collaborator."
       render :new
     end
  end
  
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include ApplicationHelper

  def index
   @user = current_user
   if current_user.admin? || current_user.premium?
     @wikis = Wiki.all
   elsif current_user.standard?
     @wikis = Wiki.where(private: false)
     @wikis += Wiki.where(private: nil)
   end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
 # #9
    @wiki = Wiki.new()
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user


 # #10
    if @wiki.save
 # #11
       flash[:notice] = "Wiki was saved."
       redirect_to wikis_path
    else
 # #12
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
    end
  end
  
  def edit
    @users = User.all
    @wiki = Wiki.find(params[:id])
  end
  
  def update
   @wiki = Wiki.find(params[:id])
   @wiki.title = params[:wiki][:title]
   @wiki.body = params[:wiki][:body]
   @wiki.private = params[:wiki][:private]
   
 
   if @wiki.save
     flash[:notice] = "Wiki was updated."
     redirect_to wikis_path
   else
     flash.now[:alert] = "There was an error saving the wiki. Please try again."
     render :edit
   end
  end
  
  def destroy
     @wiki = Wiki.find(params[:id])
 
 # #8
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
      
  def markdown(text)

    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer)

    markdown.render(text)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/charges/validate.html.erb
<h1>Are you sure you want to downgrade your membership?</h1>
<%= link_to "Downgrade Membership", charges_downgrade_path, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to downgrade your membership?  Remember your private wikis will become public.' } %>

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>

<div>
  <%= link_to "Add Collaborator", new_wiki_collaborator_path, class: 'btn btn-info' %>
</div>
<% end %>
	

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>

<%= form_for [@wiki, @coll] do |f| %>

  <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <%= form_group_tag(@wiki.errors[:user]) do %>
    <%= f.label :user %>
    <%= f.select :user_id, options_from_collection_for_select(User.all, "id", "email") %>
  <% end %>

  <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? && current_user.standard? %>
     Signed in as: <strong><%= current_user.email %></strong> |
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> - <%= link_to "Blocipedia", root_path, :class => 'navbar-link' %> - <%= link_to "Wiki Index Page", wikis_path, :class => 'navbar-link' %>
     - <%= link_to "Upgrade to Premium Membership", new_charge_path, :class => 'navbar-link' %>
    <% elsif user_signed_in? && current_user.premium? %>
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> - <%= link_to "Blocipedia", root_path, :class => 'navbar-link' %> - <%= link_to "Wiki Index Page", wikis_path, :class => 'navbar-link' %>
     - <%= link_to "Downgrade to Standard Membership", charges_validate_path, :class => 'navbar-link' %>
    <% else %>
     <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
     <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
   
   <% if flash[:notice] %>
      <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>The best place for information about Bloc.</p>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class ="form-group">
         <%= render partial: 'wikis/form', locals: { f: f } %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/index.html.erb
 <h1>All Wikis</h1>
 
<div class="col-md-4">
 <%= link_to "New", new_wiki_path, class: 'btn btn-success' %>
</div>
<br><% @wikis.each do |wiki| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to markdown(wiki.title), wiki %>
       </h4>
     </div>
   </div>
 <% end %>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
        <%= render partial: 'wikis/form', locals: { f: f } %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
   <div>
      <h1><%= markdown(@wiki.title) %> </h1>
      <h3> <%= markdown(@wiki.body) %> <br>
         submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %> </h3>
   </div>
   
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path, class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
   </div>

<div>
   <br>
   <br>
   <% User.all.each  do |user| %>
      <%= user.email %>
      <% if @wiki.users.include? user %>
         <%= link_to "Delete collaborator", collaborator_path(id: Collaborator.last.id, wiki_id: @wiki.id, user_id: user.id), method: :delete %>
      <% else %>
        <%= link_to "Add collaborator", collaborators_path(wiki_id: @wiki.id, user_id: user.id), method: :post %>
      <% end %>
      <br>
   <% end %>

</div>